SecureApiGateway/secure-api-gateway-fapi-pep-as

config/7.3.0/fapi1part2adv/ig/routes/routes-service/01-rs-example-fapi-protected-api.json
Renaming the example RS API route to make it clearer that this is an example API that is being protected using FAPI.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1291
=> 1291: Renaming the example RS API

config/7.3.0/fapi1part2adv/ig/routes/routes-service/01-rs-example-fapi-protected-api.json, config/7.3.0/fapi1part2adv/ig/scripts/groovy/ExampleRsApiResponseHandler.groovy
OIDF conformance suite requires a 200 or 201 response.
Updating the example API route to call a handler which returns a 200 response and has a json payload containing the user's id from the access_token.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1295
=> 1295: Enhancing the example API response to contain data

config/7.3.0/fapi1part2adv/ig/routes/routes-service/76-jwkms-test-directory-jwks.json, secure-api-gateway-core-docker/Dockerfile
Removing the bcprov-jdk18on-1.74.jar from the IG Docker image as this clashes with the version used by SAPI-G. This dependency was previously not present in the IG docker image. Going forwards, when we upgrade IG we will need to update the rm command to delete the correct version.
Fixing the Test Trusted Directory JWKS route to set the key usage as VERIFY. The key usage of SIGN is used to expose a private key in a JWKS, which we do not want to do, we only wish to expose the public key portion which clients can use to verify sigs.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1335
=> 1335: Fixing Test Trusted Directory to be compatible with IG 2024.3

config/7.3.0/fapi1part2adv/ig/config/dev/config/config.json, config/7.3.0/fapi1part2adv/ig/config/prod/config/config.json, config/7.3.0/fapi1part2adv/ig/routes/routes-service/20-as-dcr-endpoint.json, config/7.3.0/fapi1part2adv/ig/scripts/groovy/ProcessRegistration.groovy
Using the ProcessRegistration.groovy from the OB deployment in order to support OB DCRs in SAPI-G core. This enables TPPs to use core with OB certs and SSAs, which makes testing (particularly configuring OIDF conformance suites) easier.
Adding config to trust the OB directory TLS certs.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1338
=> 1338: Support OB DCRs in core

config/7.3.0/fapi1part2adv/ig/routes/routes-service/20-as-dcr-endpoint.json, config/7.3.0/fapi1part2adv/ig/scripts/groovy/ProcessRegistration.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/SecureApiGatewayClassAliasResolver.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/common/ResponseFactory.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/FapiInteractionIdTracingFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/FapiUtils.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/FapiAdvancedDCRValidationFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/metrics/RouteMetricsFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/FapiInteractionIdTracingFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/FapiUtilsTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/FapiAdvancedDCRValidationFilterTest.java
Fapi is the preferred class prefix when referring to FAPI standard.
Renaming the following:
- FAPIUtils -> FapiUtils
- FAPIAdvancedDCRValidationFilter -> FapiAdvancedDCRValidationFilter
https://github.com/SecureApiGateway/SecureApiGateway/issues/1117
=> 1117: Rename classes to use Fapi prefix for consistency

config/7.3.0/fapi1part2adv/ig/routes/routes-service/20-as-dcr-endpoint.json, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/SecureApiGatewayClassAliasResolver.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/request/RegistrationRequestBuilderFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/request/RegistrationRequestBuilderFilterTest.java
The filter builds RegistrationRequest objects from the HTTP request and adds them to the Context so that other filters can process them, renaming the RegistrationRequestEntityValidatorFilter filter to RegistrationRequestBuilderFilter to better capture what it is doing.
The previous name was misleading as it was not applying any validation rules to the request.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1116
=> 1116: Rename RegistrationRequestEntityValidatorFilter to RegistrationRequestBuilderFilter

config/7.3.0/fapi1part2adv/ig/config/dev/config/config.json, config/7.3.0/fapi1part2adv/ig/config/prod/config/config.json
Removing the optional version configuration of AmService, using the AM version discovery functionality in IG.
This avoid having a misconfiguration when the AM version is upgraded / is different in different environments.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1377
=> 1377: Use version discovery functionality of AmService

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/FapiInteractionIdTracingFilter.java
Logging the interactionId value in FapiInteractionIdTracingFilter rather than the Optional which wraps the value.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1114
=> 1114: Fixing logging of x-fapi-interaction-id in FapiInteractionIdTracingFilter

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/filter/AuthorizeResponseFetchApiClientFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/filter/ParResponseFetchApiClientFilterHeaplet.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/filter/ParResponseFetchApiClientFilterTest.java
client_id is now extracted from the request JWT's claim of the same name.
The previous impl was incorrect, as it assumed that the client_id was always present as a form param. This is only the case due to OPENAM-21910 bug in AM. The new impl will is correct as per the spec and will continue to work when the bug is fixed in AM.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1379
=> 1379: Retrieve client_id from request object JWT for PAR

config/7.3.0/fapi1part2adv/ig/config/dev/config/config.json, config/7.3.0/fapi1part2adv/ig/config/prod/config/config.json, config/7.3.0/fapi1part2adv/ig/routes/routes-service/01-rs-example-fapi-protected-api.json
The MTLS validation is the main purpose of the chain, the resources are fetched in order to carry this out.
The new name makes validation being carried out more obvious when the chain name is read in a route definition.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1387
=> 1387: Renaming FetchApiClientResourcesChain to ValidateApiClientMtlsCertChain

Makefile
Multiple make commands was creating multiple docker images with a single tag, want to have a single docker image with multiple tags
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1389
=> 1389: Use CI Repo for standardised steps in github workflows

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/metrics/MetricsContextSupplier.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/metrics/RouteMetricsFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/metrics/TokenEndpointMetricsContextSupplier.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/metrics/RouteMetricsFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/metrics/TokenEndpointMetricsContextSupplierTest.java
MetricsContextSupplier interface now returns a Promise.
TokenEndpointMetricsContextSupplier implements MetricsContextSupplier, and now accesses the Request's Form entity asynchronously; which removes the blocking IO call. 
https://github.com/SecureApiGateway/SecureApiGateway/issues/1115
=> 1115: Remove blocking IO call in TokenEndpointMetricsContextSupplier

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/common/jwt/ClaimsSetFacade.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/RegistrationRequest.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/SoftwareStatement.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/FapiAdvancedDCRValidationFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/FapiAdvancedDCRValidationFilterTest.java
The RegistrationRequest sourced from the AttributesContext is validated by the filter. This removes duplicate logic for extracting the data from the HTTP request entity directly.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1400
=> 1400: Using RegistrationRequest object in FapiAdvancedDCRValidationFilter validation

config/7.3.0/fapi1part2adv/ig/routes/routes-service/22-as-par-endpoint.json, config/7.3.0/fapi1part2adv/ig/scripts/groovy/FixParParamsForAm.groovy
An AM bug exists which requires the client_id param be supplied in all calls to the /par endpoint, see https://bugster.forgerock.org/jira/browse/OPENAM-21910
According to the spec, the client_id is only required when it is needed as an authentication param i.e. when the client is doing tls_client_auth. If the client is doing private_key_jwt auth then the client_id is not a required param.
This workaround uses a filter to add the client_id param if it is missing, the value is sourced from the request JWT param's iss claim.
The workaround is best-effort, if an error occurs it is ignored and the call is allowed to pass through to AM.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1417
=> 1417: Add workaround for AM PAR endpoint bug requiring client_id param

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/jws/RsaJwtSignatureValidator.java
Throwing SignatureException instead of IllegalStateException, this means that validation errors do not get wrapped in another exception. The issue with wrapping the exception is that the class of the wrapped exception gets output in the error message, which leaks impl details to the client.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1406
=> 1406: Improve RsaJwtSignatureValidator errors

config/7.3.0/fapi1part2adv/ig/config/dev/config/config.json, config/7.3.0/fapi1part2adv/ig/config/prod/config/config.json
Update variable placeholder for any config that uses the jwkms endpoint to use new test trusted directory FQDN
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/846
=> 846: Create DNS for new stand alone test trusted directory and update relevant configs

config/7.3.0/fapi1part2adv/ig/config/dev/config/config.json, config/7.3.0/fapi1part2adv/ig/config/prod/config/config.json
This switches from supporting SSAs with an embedded JWKS to using a jwks_uri to fetch the JWKS for the client from the directory.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1428
=> 1428: Configure Test Trusted Directory to use SSA jwks_uri claim

pom.xml, secure-api-gateway-core-docker/Dockerfile
Bump docker image and Pom version to latest release version 2024.6.0
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1475
Testing: PR Image running on dev-core
Test Result: https://g.codefresh.io/build/6686ac05c60584a75fc47734
=> 1475: Upgrade openIG to 2024.6 ready for SAPIG 3.1.0

pom.xml
- Nimbus to 9.40
- Bouncy castle to 1.78.1
- Parent pom to 3.0.1-SNAPSHOT
https://github.com/SecureApiGateway/SecureApiGateway/issues/1473
=> 1473: Update nimbus and bouncy castle dependencies

secure-api-gateway-core-docker/7.3.0/ig/bin/import-pem-certs.sh
Change IG_PEM_TRUSTSTORE from being required by the import script, will perform the first import which IG relies on, and then perform further actions if IG_PEM_TRUSTSTORE has a value
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1507
=> 1507: Support making ig-truststore-pem secret optional for core deployment

config/7.3.0/fapi1part2adv/ig/routes/routes-pod/98-kube-probe.json, config/7.3.0/fapi1part2adv/ig/routes/routes-service/99-platform-passthrough.json
Rename 29-as-passthrough.json to 99-platform-passthrough.json
The route is now responsible for passing any requests, which have not already been routed, through to the Identity Platform.
This includes AM endpoints such as the XUI and IDM endpoints to fetch config used to render the XUI.
Fix name of 98-kube-probe.json route to ensure that it is ordered before the pass-through route.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1512
=> 1512: Make pass-through route send all traffic to Identity Platform

config/7.3.0/fapi1part2adv/ig/config/dev/config/admin.json, config/7.3.0/fapi1part2adv/ig/config/prod/config/admin.json
Deprecated option: maxHeaderSize replaced with maxTotalHeadersSize
Configuring the new option as 24KB, as the previous config allowed a max individual header size of 16KB, typically there is one large header (a JWT etc).
https://github.com/SecureApiGateway/SecureApiGateway/issues/1521
=> 1521: Update server side vertx max header config

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/common/jwt/AuthorizeRequestParameterNames.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/authorize/BaseFapiAuthorizeRequestValidationFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/authorize/FapiAuthorizeRequestValidationFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/authorize/FapiParRequestValidationFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/authorize/BaseFapiAuthorizeRequestValidationFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/authorize/FapiAuthorizeRequestValidationFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/authorize/JWTSigner.java
AM doesn't ignore request parameters when a JAR is used for the authorize request as required by RFC 9101. This means we fail some tests in the FAPI 1.0 - Part 2: Advanced + PAR test suite.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1542
=> 1542: Remove auth params from http request for /authorize & /par endpoints

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/common/jwt/AuthorizeRequestParameterNames.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/authorize/BaseFapiAuthorizeRequestValidationFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/authorize/FapiAuthorizeRequestValidationFilter.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/authorize/FapiParRequestValidationFilter.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/authorize/BaseFapiAuthorizeRequestValidationFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/authorize/FapiAuthorizeRequestValidationFilterTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/authorize/FapiParRequestValidationFilterTest.java
Addition and modifications to the AuthorizeRequestValidationFilters such that PAR requests that don't contain the following claims are rejected;  
`code_challenge`
`code_challenge_method`
Furthermore, the `code_challenge_method` claim must be equal to `S256`. This is necessary for FAPI 1.0 - Part 2: Advanced + PAR conformance testing
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1545
=> 1545: Reject PAR with non FAPI PKCE fields in JAR

secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/fapi/v1/authorize/BaseFapiAuthorizeRequestValidationFilterTest.java
Use the method to get the JAR request claims rather than hard coding them. This is now consistent across the test class
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1545
=> 1545: Tidy up test class

config/7.3.0/fapi1part2adv/ig/scripts/groovy/ProcessRegistration.groovy
Fixing bug introduced in: https://github.com/SecureApiGateway/secure-api-gateway-core/pull/76
A request object was incorrectly being returned instead of a response.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1521
=> 1547: Fix ProcessRegistration.groovy

secure-api-gateway-ig-extensions/pom.xml
Remove setting to set openig-fapi as provided
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1620
=> 1420: Build V4 OB IG with latest version of Core

config/7.3.0/fapi1part2adv/ig/config/dev/config/config.json, config/7.3.0/fapi1part2adv/ig/config/prod/config/config.json
1620: Align core with SAPIG OB UK prod config.json following move to core IG components (openig-fapi)
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1620
=> 1620: Align core with SAPIG OB UK prod config.json following move to core IG components

pom.xml, secure-api-gateway-core-docker/Dockerfile, secure-api-gateway-core-docker/pom.xml, secure-api-gateway-ig-extensions/pom.xml
OPENIG-8856: Include openig-fapi in core IG standalone deliverable, to be picked up in SAPIG-core.
Test IG FAPI-enabled image deployment (removing explicit dependency on IG's openig-fapi module).
=> OPENIG-8856: Consume FAPI-enabled IG standalone deliverable (image)

pom.xml, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/mtls/DefaultTransportCertValidator.java, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/mtls/TransportCertValidator.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/mtls/DefaultTransportCertValidatorTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/mtls/ResponsePathTransportCertValidationFilterTest.java
Update following COMMONS fix to use VerificationKey for "tls' use.
Update propagated through OPENIG-9142 in IG repo.
IG PR: https://stash.forgerock.org/projects/OPENIG/repos/openig/pull-requests/6723/overview
COMMONS: https://stash.forgerock.org/projects/COMMONS/repos/forgerock-commons/pull-requests/2670/builds
=> OPENIG-9142 Change CachingJwkSetService to use VerificationKey purpose.

config/7.3.0/fapi1part2adv/ig/routes/routes-service/20-as-dcr-endpoint.json, config/7.3.0/fapi1part2adv/ig/scripts/groovy/ProcessRegistration.groovy, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/scripts/ProcessRegistrationTest.java
Fixes:
1. Fix `ProcessRegistration` transport cert validation (should use configured "tls" purpose). Added new `ProcessRegistraton` script config item `tlsTransportCertSecretId` allowing us to now pass the purpose label in (corresponding with where it's used elsewhere. This was broken with changes in the IG PR.
2. Fixed failing core test `FapiDynamicClientRegistrationTest.MtlsTests#MtlsTests` caused because the `#getValid` call allows no secrets to be supplied (which I now have to convert to my own `NSSE`).
3. Fixed failing core test `FapiDynamicClientRegistrationTest.RequestJwtSigningTests#failsIfRequestJwtSignedByKeyWithIncorrectUse()` [failure](https://g.codefresh.io/build/67e12e478c6d39b1d888dbc8?activeAccountId=5bc76f3a8249cc15fa883acb&step=run_tests&tab=output&logs=terminal), caused …
=> OPENIG-9142 Fix ProcessRegistration transport cert validation

config/7.3.0/fapi1part2adv/ig/routes/routes-service/20-as-dcr-endpoint.json, config/7.3.0/fapi1part2adv/ig/routes/routes-service/21-as-token-endpoint.json, config/7.3.0/fapi1part2adv/ig/routes/routes-service/22-as-par-endpoint.json
Due to OPENIN-9209 changes, the configuration to retrieve the client certificate must be updated to use the new Expression.
=> OPENIG-9209 Update client certificate configuration

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/metrics/RouteMetricsFilter.java
While fixing another issue there were a lot of errors logged stating;
`Failed to publish metrics due to exception`
This PR fixes that code by making the api client optional again, because depending on the request is not always present. 
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1686
=> 1686: Fix missing FapiContext exception

config/7.3.0/fapi1part2adv/ig/scripts/groovy/ProcessRegistration.groovy, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/scripts/ProcessRegistrationTest.java
ApiClient has been migrated to the new FapiContext, so ProcessRegistrationProcess needs to use the new location.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1687
=> 1687: use new FapiContext to retrieve ApiClient

config/7.3.0/fapi1part2adv/ig/config/dev/config/config.json, config/7.3.0/fapi1part2adv/ig/config/prod/config/config.json, config/7.3.0/fapi1part2adv/ig/routes/routes-service/20-as-dcr-endpoint.json, config/7.3.0/fapi1part2adv/ig/scripts/groovy/ProcessRegistration.groovy, secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/mtls/DefaultTransportCertValidator.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/mtls/DefaultTransportCertValidatorTest.java, secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/mtls/ResponsePathTransportCertValidationFilterTest.java
Objective:
Just expose the purposes used for use by client code, so as to reduce config and risk or config error.
Now client code can get the appropriate Purpose to use to obtain the specific key, rather than risk supplying the wrong one (via docs, etc).
=> OPENIG-9122 Expose the CachingJwkSetService purposes used to obtain secrets, for use by client code

_infra/helm/secure-api-gateway-fapi-pep-as/templates/ingress.yaml, config/7.3.0/fapi1part2adv/ig/config/dev/config/config.json, config/7.3.0/fapi1part2adv/ig/routes/routes-service/28-as-metadata.json
The authorization_endpoint value in the OIDC wellknown response is currently not the mtls endpoint. This means when using tls_client_auth as the token_endpoint_auth method, no certificate is available for mTLS processing on the authorize endpoint.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1696
=> 1696: authorization_endpoint will be on mTLS endpoint

_infra/helm/secure-api-gateway-fapi-pep-as/Chart.yaml
Bump helm version, release action already ran, but checked the Chart.yaml from maven artifactory and the version has been changed during release process, so this is just clean up work
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1703
=> 1703: Create SAPIG 5.0.0

.github/workflows/pr.yml, pom.xml, secure-api-gateway-fapi-pep-as-docker/Dockerfile, secure-api-gateway-fapi-pep-as-docker/pom.xml, secure-api-gateway-ig-extensions/pom.xml
Based off of V5.0.0
Updated version to `5.0.1-SNAPSHOT`
Updated openIG version to `2025.6.2`
Updated Dockerfile to `gcr.io/forgerock-io/ig:2025.6.2-fapi`
Issue: https://pingidentity.atlassian.net/browse/OPENIG-9573
=> OPENIG-9573: SAPIG 5.0.1 Release
