README.MD

https://github.com/SecureApiGateway/SecureApiGateway/issues/1295

1295: Adding README.MD

---

.github/workflows/merge.yml
.github/workflows/pr.yml

Deploy steps for PR and Merge, PR commented out until individual envs are required
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1304

1304: Create dev deployment of SAPI-G core

---

.github/workflows/merge.yml

Run the make command to build a dev IG docker image and push to artifact registry
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1328

1328: Change Individual Environments to use a dev IG Image

---

.github/workflows/merge.yml
.github/workflows/pr.yml

Update service name in workflows
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1331

1331: Fix Core Workflows

---

config/7.3.0/fapi1part2adv/ig/routes/routes-service/72-jwkms-apiclient-getssa.json
config/7.3.0/fapi1part2adv/ig/routes/routes-service/76-jwkms-test-directory-jwks.json

KeyStoreSecretStore config items updated:
storePassword -> storePasswordSecretId
keyEntryPassword -> entryPasswordSecretId
https://github.com/SecureApiGateway/SecureApiGateway/issues/1159

1159: Fixing deprecated KeyStoreSecretStore config

---

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/common/DCRErrorCode.java
secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/fapi/v1/FapiAdvancedDCRValidationFilter.java

https://github.com/SecureApiGateway/SecureApiGateway/issues/1143

1143: Cleanup javadoc for FapiAdvancedDCRValidationFilter

---

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/filter/FetchApiClientFilter.java
secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/filter/ManageApiClientFilter.java
secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/sigvalidation/RegistrationRequestJwtSignatureValidationFilter.java
secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/jwks/FetchApiClientJwksFilter.java
secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/metrics/RouteMetricsFilter.java
secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/trusteddirectories/FetchTrustedDirectoryFilter.java
secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/util/ContextUtils.java
secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/filter/BaseResponsePathFetchApiClientFilterTest.java
secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/filter/ManageApiClientFilterTest.java
secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/jwks/FetchApiClientJwksFilterTest.java
secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/mtls/ResponsePathTransportCertValidationFilterTest.java
secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/mtls/TransportCertValidationFilterTest.java
secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/FetchTrustedDirectoryFilterTest.java
secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/util/ContextUtilsTest.java

Adding ContextUtils class with a helper method for fetching attributes from the Context and returning them as a specified type.
Updating classes which retrieve data from the attributes context to use the util method.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1400

1400: Creating helper methods for getting attributes from the Context

---

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/request/RegistrationRequestBuilderFilter.java
secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/request/RegistrationRequestBuilderFilterTest.java

A race condition was observed in the filter, due to it using a shared builder instance, this resulted in data being for one request being overwritten by data from another.
Fixing this issue by creating new builders per request being processed. 
Created test case: shouldSucceedWhenCalledConcurrently , which demonstrated that the filter had a race conditon, now that the fix has been applied the test is passing. The test invokes the filter by multiple threads, each task submits a unique registration request payload and expects to the RegistrationRequest object created by the filter to match this data.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1402

1402: Fixing race condition in RegistrationRequestBuilderFilter

---

.github/workflows/release.yml
Makefile

Show release number in workflow name
Use main branch for calling ci repo
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1389

1389: Use CI Repo for standardised steps in github workflows

---

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/request/RegistrationRequestBuilderFilter.java
secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/request/RegistrationRequestEntitySupplier.java

The previous impl was doing blocking IO, which will cause issues if IG is in streaming mode.
https://github.com/SecureApiGateway/SecureApiGateway/issues/1427

1427: Make RegistrationRequestEntitySupplier asynchronous

---

.github/workflows/codeql.yml
.github/workflows/merge.yml
.github/workflows/pr.yml

Enable manual trigger for PR and Merge workflows
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1465

1465: Allow Manual run of workflows

---

secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/models/ApiClient.java
secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/service/idm/IdmApiClientDecoder.java
secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/dcr/models/ApiClientTest.java
secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/jwks/DefaultApiClientJwkSetServiceTest.java
secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/trusteddirectories/FetchTrustedDirectoryFilterTest.java

https://github.com/SecureApiGateway/SecureApiGateway/issues/1114

1114: Cleanup ApiClient & ApiClientBuilder

---

.github/workflows/merge.yml

Add in the branch that is being updated
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1513

1513: Fix Core Deployment on merge

---

pom.xml
secure-api-gateway-core-docker/Dockerfile

Upgrade IG Version from` 2024.6.0` -> `2024.9.0`
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1540

1540: Upgrade OpenIG to 2024.9.0

---

config/7.3.0/fapi1part2adv/ig/scripts/groovy/ASWellKnownFilter.groovy
config/7.3.0/fapi1part2adv/ig/scripts/groovy/ProcessRegistration.groovy

Fixing the following scripts to use getJsonAsync in order to avoid blocking:
- ASWellKnownFilter.groovy
- ProcessRegistration.groovy
https://github.com/SecureApiGateway/SecureApiGateway/issues/1547

1547: Use getJsonAsync in groovy scripts

---

config/7.3.0/fapi1part2adv/ig/scripts/groovy/ErrorResponseFilter.groovy

Not returning the promise correctly!
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1546

1546: Fix error when HTTP response is not a client error

---

config/7.3.0/fapi1part2adv/ig/scripts/groovy/ErrorResponseFilter.groovy

Groovy may have worked before, but this code make it more explicit what is happening and hence is more readable.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1546

1456: Return a promise containing the response

---

pom.xml

~~Bump Version to `4.0.4-SNAPSHOT` ready for release~~
Revert Parent to `4.0.0` as no changes in repo to be released
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1642

1642: Create SAPIG 4.0.4

---

Makefile

Update service name in makefile
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1676

1676: Split IG into AS/RS and deploy to Devenvs

---

config/7.3.0/fapi1part2adv/ig/routes/routes-service/20-as-dcr-endpoint.json
config/7.3.0/fapi1part2adv/ig/routes/routes-service/21-as-token-endpoint.json
config/7.3.0/fapi1part2adv/ig/routes/routes-service/22-as-par-endpoint.json
config/7.3.0/fapi1part2adv/ig/routes/routes-service/23-as-authorize-endpoint.json

Name of the configuration for the certificate header name has been renamed and should be fixed.

fixing wrong configuration

---

Makefile
_infra/helm/secure-api-gateway-fapi-pep-as/Chart.yaml
_infra/helm/secure-api-gateway-fapi-pep-as/readme.md
_infra/helm/secure-api-gateway-fapi-pep-as/templates/configmap.yaml
_infra/helm/secure-api-gateway-fapi-pep-as/templates/deployment.yaml
_infra/helm/secure-api-gateway-fapi-pep-as/templates/ingress.yaml
_infra/helm/secure-api-gateway-fapi-pep-as/templates/secret.yaml
_infra/helm/secure-api-gateway-fapi-pep-as/templates/service.yaml
_infra/helm/secure-api-gateway-fapi-pep-as/values.yaml
_infra/kustomize/base/configmap.yaml
config/7.3.0/fapi1part2adv/ig/config/dev/config/config.json
config/7.3.0/fapi1part2adv/ig/config/prod/config/config.json

Add in helm packages
Changes to standardise TTD FQDN
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1679

1679: Migrate IG Components to Helm

---

.github/workflows/pr-helm.yml
_infra/helm/secure-api-gateway-fapi-pep-as/Chart.yaml

- Add in helm pr workflow
- Adjust Helm Chart for test release
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1682

1682: Use new Helm files to deploy to Relenv

---

_infra/helm/secure-api-gateway-fapi-pep-as/values.yaml
config/7.3.0/fapi1part2adv/ig/routes/routes-service/21-as-token-endpoint.json
secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/am/AccessTokenResponseIdTokenReSignFilter.java
secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/am/AuthorizeResponseJwtReSignFilter.java
secure-api-gateway-ig-extensions/src/test/java/com/forgerock/sapi/gateway/am/AuthorizeResponseJwtReSignFilterTest.java

- Add in AccessTokenResponseIdTokenReSignFilter to `token endpoint` route
- Add OB Signing Key dummy values to values.yaml
Issue: https://pingidentity.atlassian.net/browse/OPENIG-9515

OpenIG-9515: FAPI Conformance Suite (Tests)
